### ISSUE TITLE
[SoftDeleteable] Deleted entities showing up on eager fetches

### ISSUE THREAD

**Issue by sonu27** [Atlantic18/DoctrineExtensions#1463] opened 2015-11-25 10:09 UTC
Using v2.4.7 and Symfony 2.7.7 (also tested on Symfony 2.7.6), if I use `fetch="EAGER"` on one-to-many relations the "deleted" entities appear in the results.

E.g.
`<one-to-many field="items" target-entity="BasketItem" mapped-by="basket" fetch="EAGER">
      <cascade>
        <cascade-all/>
      </cascade>
    </one-to-many>`

Is this desired behaviour? Could I be doing something wrong?

```
orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                connection:    default
                mappings:
                    AppBundle: ~
                result_cache_driver:
                    type: redis
                    host: "%redis_host%"
                    instance_class: Redis
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
```

**Comment by l3pp4rd** [comment] 2015-11-26 15:44
it might be that eager fetching does not hit filter, so far I do not know how you could by pass it.. but in the end it is better to handle softdeletion manually. managing softdeleted relations is though task.

**Comment by sonu27** [comment] 2015-11-27 12:21
Found someone else with the same problem it seems: http://sofd.developer-works.com/article/21370516/Doctrine+2+filtering+with+EAGER+relations

**Comment by datasage** [comment] 2015-11-28 01:20
How EAGER mapping is handled has changed with doctrine 2.5. It now uses a join instead of two separate queries. The filter does not get added to the join.

**Comment by l3pp4rd** [comment] 2015-11-30 18:56
I see, if that is possible, maybe there is a way to hook it in sql filter, if that issue is a concern, you could have a look

**Comment by semen4eg** [comment] 2015-12-25 14:04
Tried to find a workaround that problem.
Added posibility to suply eager relations like that:
```
/**
 * @ORM\Table()
 * @ORM\Entity
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, eager={"template_view"})
 */
```

in filter listener
```
public function addFilterConstraint(ClassMetadata $targetEntity, $targetTableAlias)
```

added a code to handle configuration param
```
if(isset($config['eager']) && $config['eager'])
{
	$mainCondition = "({$addCondSql})";
	$softColumn = $targetEntity->getQuotedColumnName($config['fieldName'], $platform);
	$platform = $conn->getDatabasePlatform();

	foreach($config['eager'] as $eagerRelation)
	{
		$softCondition = $platform->getIsNullExpression($eagerRelation.'.'.$softColumn);
		$addCondSql = "{$mainCondition} AND ({$softCondition})";
	}
}
```

That would generate query:
```
SELECT ... FROM template t0 LEFT JOIN template_view t5 ON t5.template_id = t0.id 
WHERE (((t0.deleted_at IS NULL) 
AND (template_view.deleted_at IS NULL)))':
```

The problem is that there is no way to find out what is the alias for template_view table

**Comment by l3pp4rd** [comment] 2016-03-16 12:06
I see @Wobbly-Wibbly in general softdeleteable does not fit its concept well with orm, most of the users fallback to managing it manually, same for myself in such cases sadly. Keeping it open since there is no obvious solution so far

**Comment by sonu27** [comment] 2016-03-16 15:09
Nowadays, Soft deletes are an anti-pattern but many legacy projects use it.

However, it might be worth mentioning this compatibility problem on the SoftDeleteable docs.

**Comment by datasage** [comment] 2016-03-16 15:25
While there are better ways to solve the problems (logging, auditing, archiving) that soft delete is intended to solve. It is an easy option to use when time or resources are not available to implement a better option. Its also very easily understood.

Of course it can other problems later, depending on the application, so its a tradeoff.

**Comment by Padam87** [comment] 2016-03-16 15:31
Softdelete is definitely not an anti-pattern. Some computer science people may think so, but real word use cases, and RAD requires the softdeleteable pattern.

I wrote a failing test for this issue: https://github.com/Atlantic18/DoctrineExtensions/pull/1550

Unfortunately, It should be fixed by doctrine.

**Comment by l3pp4rd** [comment] 2016-03-16 16:02
thanks for the input, will need to mention this in documentation.

**Comment by seyfer** [comment] 2017-10-19 10:39
Did somebody create an issue in Doctrine about that issue?

**Closed** 2020-11-01 17:21 UTC
Labels: Documentation
