### ISSUE TITLE
[Sortable] Positions are updated on entity remove, even if removing failed

### ISSUE THREAD

**Issue by naitsirch** [Atlantic18/DoctrineExtensions#1209] opened 2014-12-31 10:11 UTC
The *Sortable* extension updates the position of entities if an entity is scheduled to be removed. But if the removing fails (e.g. on foreign key constraint violence) the positions still get updated, what leads to wrong positioning.

### Example

**Table A**

ID | Name | Position [sortable]
--- | ------- | ----------------------
1 | aaa | 1
2 | bbb | 2
3 | ccc | 3

**Table B**

FK-to-table-A [onDelete `restrict`] | Name 
---------------------------------------- | --------
2 | I like bbb

Now, we tell doctrine to remove entity 2 from **Table A** with
```php
/* @var $em EntityManager */
try {
    $em->remove($entity2);
    $em->flush();
} catch (ForeignKeyConstraintViolationException $e) {
    // ...
}
```
Because of the foreign key contraint violation the entity won't be removed from database. But at the end of this action **Table A** will look like that:

ID | Name | Position [sortable]
--- | ------- | ----------------------
1   | aaa   | 1
2   | bbb   | ***1***
3   | ccc    | ***2***

So the position has been decreased.

**Comment by naitsirch** [comment] 2015-01-05 15:01
After investigeting into this issue I found out, that the decreement of the position field happens before the db transaction starts, which means that the rollback on exception does not roll back the changes of the positions.
Maybe this is the reason. I'll try to look deeper into this.

**Comment by naitsirch** [comment] 2015-01-06 08:01
The problem is, that the position relocations are processed in `onFlush` event. At this time doctrine has not started the transaction. So that the rollback after the exception does not roll back the changes of the position.

It seems to work, when the call of `processRelocations()` is moved to other events. I'll test this and create a PR if no tests will break.

**Comment by leonex-cstoller** [comment] 2015-01-08 10:55
After investigeting into this issue I found out, that the decreement of the position field happens before the db transaction starts, which means that the rollback on exception does not roll back the changes of the positions.

The problem is, that the position relocations are processed in `onFlush` event. At this time doctrine has not started the transaction.

It seems to work, when the call of `processRelocations()` is moved to other events. I'll test this and create a PR if no tests will break.

**Comment by leonex-cstoller** [comment] 2015-02-25 07:36
@l3pp4rd this issue could be closed, after the PR is merged ;-)

**Closed** 2015-02-25 18:02 UTC

**Comment by naitsirch** [comment] 2015-02-25 18:58
That's great. Thanks!
