### ISSUE TITLE
SoftDeleteable Query cache invalidation

### ISSUE THREAD

**Issue by maryo** [Atlantic18/DoctrineExtensions#1146] opened 2014-08-27 07:59 UTC
Hi. Check this
http://www.doctrine-project.org/jira/browse/DDC-3174

Filters cannot be stateful. If you check this code:
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Query.php#L685
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Query/FilterCollection.php#LC202

You can see that only the name and the fact if it is disabled (the whole filter) or not is input for cache key.

So if you call just  `$filter->disableForEntity` then the whole filter is still enabled, just its state is changed => the cache key is not properly invalidated in this scenario.

One solution is disabling query cache manually for these scenarios (= no change but updating the documentation).
Better solution would probably need PR to Doctrine.
Other ideas?

**Comment by four43** [comment] 2015-02-04 18:55
We ran into a similar issue. Our use case using timeAware:

Looking to cache some of the DQL queries using Doctrine's built in queryCache.
```PHP
$query->useQueryCache(true);
```
Nothing fancy, but this does not work when using the SoftDeleteable plugin because it is caching the first time the filter is used. Since the filter uses application time instead of `NOW()` for example, Doctrine caches the query, stringified timestamp included and uses that for subsequent queries. Steps to see this behavior in action.

1. Query for a list of deletable objects (query cached with 2015-01-01 00:00:00 for example)
2. Delete and object 10 seconds later (Entity's date deleted is 2015-01-01 00:00:10)
3. Query for those objects again (PROBLEM: Query will use cached value of 2015-01-01 00:00:00, (table.date_deleted IS NULL OR table.date_deleted > 2015-01-01 00:00:00), since 2015-01-01 00:00:10 is greater, it will still return our result.

I would like an option (in the annotation maybe?) to specify whether server time (NOW()) or application time (date('Y-m-d...')) gets used. I think that would be a solid work around. Thoughts on this? I could make a PR. Call the options timeMode or something like that, default to the current behavior of app time.

**Comment by stephanvierkant** [comment] 2018-05-24 10:05
Closed as duplicate of #1356.

**Closed by stephanvierkant** 2018-05-24 10:05 UTC
Labels: SoftDeleteable
